[book]
authors = ["sneakers-the-rat"]
language = "en"
multilingual = false
src = "src"
title = "p2p-ld"

[preprocessor.bib]
bibliography = "p2p_ld_docs.bib"
render-bib = "cited"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
site-url = "/docs/"
git-repository-url = "https://github.com/p2p-ld/docs"
git-repository-icon = "fa-github"
additional-js = ["mermaid.min.js", "mermaid-init.js"]